on:
  pull_request:
    types: [ labeled ]
    branches:
      - main

jobs:
  prepare-release:
    name: Prepare release
    runs-on: ubuntu-latest

    steps:
      - name: Set major release
        if: ${{ github.event.label.name == 'release-major' }}
        run: echo "RELEASE=major" >> $GITHUB_ENV
      - name: Set minor release
        if: ${{ github.event.label.name == 'release-minor' }}
        run: echo "RELEASE=minor" >> $GITHUB_ENV
      - name: Set patch release
        if: ${{ github.event.label.name == 'release-patch' }}
        run: echo "RELEASE=patch" >> $GITHUB_ENV
      - name: Check release env
        run: |
          if [[ -z "${{ env.RELEASE }}" ]];
          then
            echo "You need to set a release label on PRs to the main branch"
            exit 1
          else
            exit 0
          fi
      - name: Show release version
        run: echo ${{ env.RELEASE }}
      - name: Install semver-tool
        run: |
          export DIR=$(mktemp -d)
          cd $DIR
          curl https://github.com/fsaintjacques/semver-tool/archive/3.2.0.tar.gz -L -o semver.tar.gz
          tar -xvf semver.tar.gz
          sudo cp semver-tool-3.2.0/src/semver /usr/local/bin
      - uses: actions/checkout@v2
      - name: Bump version
        run: |
          export CURRENT=$(awk -F'"' '/"version": ".+"/{ print $4; exit; }' package.json)
          export NEW_VERSION=$(semver bump ${{ env.RELEASE }} $CURRENT)
          echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV
      - name: Show version
        run: echo ${{ env.VERSION }}